[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson @ ^7.0.4
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor
  https://github.com/me-no-dev/AsyncTCP.git
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  